One big PR with issues: 4,5,6,7,8,9,10
robertb98/kanban pull request #12
Opened 2020-09-29 09:35 UTC by robertb98

2020-09-29 12:44 UTC, robertmusil requested changes

2020-09-29 12:44 UTC, robertmusil commented on backend/backend/settings.py
> +        'http://127.0.0.1:3000/auth/google/complete/',
I'd imagine this to be also in ENV

2020-09-29 12:44 UTC, robertmusil commented on backend/projects/models.py
> +    owner = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
What does models.CASCADE do?

2020-09-29 12:44 UTC, robertmusil commented on backend/projects/serializers.py
> +        extra_kwargs = {'owner': {'required': False}}
why is owner not **required**?

2020-09-29 12:44 UTC, robertmusil commented on backend/projects/urls.py
> +urlpatterns += router.urls
simplify

2020-09-29 12:44 UTC, robertmusil commented on backend/templates/email/activation.html
> +go to the following page to activate account: http://127.0.0.1:3000/{{ url|safe
again, env?

2020-09-29 12:44 UTC, robertmusil commented on backend/projects/views.py
> +        email = request.data.get('email')
is email unique? why not just pk?

2020-09-29 12:44 UTC, robertmusil commented on frontend/src/api/axios.js
> +  config.headers.Authorization = token ? `JWT ${token}` : "";
what happens when the token expires?

2020-09-30 07:25 UTC, robertb98 commented on backend/projects/models.py
> +    owner = models.ForeignKey(User, related_name='projects', on_delete=models.CASCADE)
When the user will be deleted the project would be also. When i think about it now maybe SET_NULL would be better.

2020-09-30 07:31 UTC, robertb98 commented on backend/projects/serializers.py
> +        extra_kwargs = {'owner': {'required': False}}
Because user is added in the perform_create method which takes place after the validation. I dont know if there is an option to inject him faster.

2020-09-30 07:41 UTC, robertb98 commented on frontend/src/api/axios.js
> +  config.headers.Authorization = token ? `JWT ${token}` : "";
I would want to use this.
![image](https://user-images.githubusercontent.com/22663834/94656999-1f4e2e00-0301-11eb-92f3-3920123e1b75.png)

2020-09-30 07:57 UTC, robertb98 commented on backend/projects/views.py
> +        email = request.data.get('email')
Yes email is unique. I wanted to use this endpoint with a text input on the front. If user==project.owner the input would be displayed and he could assign by email.

2020-09-30 14:18 UTC, robertmusil commented on frontend/src/api/axios.js
> +  config.headers.Authorization = token ? `JWT ${token}` : "";
```js
const a = 1;
```

2020-09-30 16:47 UTC, nitz14 commented on backend/projects/migrations/0003_auto_20200928_1144.py
> +# Generated by Django 3.1.1 on 2020-09-28 11:44
please create single migration.

2020-09-30 16:47 UTC, nitz14 commented on backend/projects/serializers.py
> +        extra_kwargs = {'owner': {'required': False}}
so maybe we shouldn't accept this field in this serializer ('read_only' ? )

2020-09-30 16:47 UTC, nitz14 commented on backend/projects/views.py
> +        return user.projects.all()
why not Projects.objects.filter(owner__pk=self.request.user.pk) or something similar ?

2020-09-30 16:47 UTC, nitz14 commented on frontend/.dockerignore
> +package-lock.json
missing empty line on end of file.

2020-09-30 16:47 UTC, nitz14 commented on frontend/src/api/userSlice.js
> +    "auth/o/google-oauth2?redirect_uri=http://127.0.0.1:3000/auth/google/complete/",
What happened when we deploy this app to some server ?

2020-09-30 16:47 UTC, nitz14 commented on frontend/src/api/userSlice.js
> +    "auth/o/github?redirect_uri=http://127.0.0.1:3000/auth/github/complete/",
like above.

2020-09-30 16:47 UTC, nitz14 commented on backend/projects/views.py
> +    authentication_classes = [JWTAuthentication]
its nesesery ?

2020-09-30 16:47 UTC, nitz14 commented on backend/account/views.py
> +        except Exception as e:
to big exception can you change it to more specific one ?

2020-09-30 16:47 UTC, nitz14 commented on backend/.dockerignore
> +Pipfile.lock
missing empty line on end of file

2020-09-30 18:42 UTC, robertb98 commented on frontend/.dockerignore
> +package-lock.json
Okey, I finally enabled this xd
![image](https://user-images.githubusercontent.com/22663834/94726375-71bd3800-035d-11eb-8f75-d1dbc7b40561.png)

2020-10-05 09:52 UTC, nitz14 commented on backend/projects/migrations/0002_project_assigned_users.py
> +# Generated by Django 3.1.1 on 2020-09-28 11:05
again can we create 1 migration ?

2020-10-05 09:52 UTC, nitz14 commented on backend/projects/views.py
> +        email = request.data.get('email')
what if user don't save this element to endpoint or what if user send email which don't exists in db ?

2020-10-05 10:52 UTC, nitz14 commented on backend/projects/views.py
> +        email = request.data.get('email')
Why you didn't use any Serializer to validate this data ?

2020-10-05 10:52 UTC, nitz14 commented on backend/projects/views.py
> +            user = User.objects.get(email=email)
maybe `get_object_or_404` will be better solution ?:)

2020-10-05 11:42 UTC, robertb98 commented on backend/projects/views.py
> +        email = request.data.get('email')
And now?

2020-10-06 09:01 UTC, nitz14 approved these changes

2020-10-09 09:58 UTC, robertmusil commented on backend/.dockerignore
> +Pipfile.lock
Why is this file in dockerignore? Isn't the whole point of this file to create reproducible builds?

2020-10-09 09:58 UTC, robertmusil commented on backend/backend/settings.py
> +        'NAME': config('POSTGRES_DB', default=os.path.join(BASE_DIR, 'db.sqlite3')),
so the name is `POSTGRES_DB`, but by default it sets up sqlite3, it all makes sense in my mind : )

2020-10-09 09:58 UTC, robertmusil commented on backend/templates/email/activation.html
> +{% block subject %}Account activation{% endblock %} {% block text_body %} Please
separate different blocks with a newline, otherwise its not readable

2020-10-09 09:58 UTC, robertmusil commented on backend/templates/email/activation.html
> +go to the following page to activate account: {{ FRONT_ADDRESS }}{{ url|safe }}
dont put *any* logic into template, url should be created in a method that sends the url, not concatenated here

2020-10-12 15:04 UTC, robertmusil approved these changes

2020-10-14 07:00 UTC, merged